#!/usr/bin/env python3
"""Task 009: capture the semantic-enrichment fixtures.

  python3 diagnostics/scripts/capture_semantic_fixtures.py produce
  python3 diagnostics/scripts/capture_semantic_fixtures.py collect [NAME ...]

produce  runs GNATprove (pinned toolchain, `alr exec` of the ring buffer)
         on the pre-registered conjunct experiment
         (tests/semantic_fixtures/conjunct_experiment/experiment.gpr).
         The benchmark cases come from the benchmarks' own scripts:
           cd examples/ring_buffer && python3 scripts/ablate_proof_support.py \
             --only no_public_model_bound no_is_empty_post no_is_full_post
           cd examples/fixed_pool && python3 scripts/ablate_proof_support.py \
             --only spec_no_count_posts
           python3 diagnostics/scripts/capture_fixtures.py produce \
             pool_false_client_assert
collect  needs an importable libadalang. For each case it copies the result
         set (sanitized like tests/fixtures, but .ali files also keep their
         D source records) to tests/semantic_fixtures/<name>/results/ and
         the SMALLEST source corpus the semantic tests need to
         tests/semantic_fixtures/<name>/src/. Every copied source must be
         the exact file GNATprove analysed: its GNAT checksum AND mtime
         must equal a D record of the result set (else: abort). Its sha256
         and D timestamp go to snapshot.json.

Git does not preserve mtimes, so the tests re-check each snapshot's sha256
and only then restore the recorded D timestamp (tests/test_semantic.py).
SPARKlib sources are not copied; the snapshot projects `with "sparklib"`
(run under `alr exec` of the example crate).
"""

from __future__ import annotations

import hashlib
import json
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
EXAMPLES = REPO / "examples"
DIAGNOSTICS = REPO / "diagnostics"
OUT = DIAGNOSTICS / "tests" / "semantic_fixtures"
sys.path[:0] = [str(DIAGNOSTICS), str(DIAGNOSTICS / "scripts")]

import capture_fixtures as cf  # noqa: E402
from spark_refine_diagnostics.ali import load_ali_sources  # noqa: E402
from spark_refine_diagnostics.gnat_checksum import gnat_checksum  # noqa
from spark_refine_diagnostics.semantic_lal import mtime_stamp  # noqa: E402

RB, FP = EXAMPLES / "ring_buffer", EXAMPLES / "fixed_pool"
EXP = OUT / "conjunct_experiment"


def _ring(case: str) -> dict:
    return {"results": RB / "obj" / f"ablation_{case}" / "gnatprove",
            "sources": [RB / "obj" / "ablation_src" / case / "ring_buffer.ads",
                        RB / "proof" / "ring_buffer_client_proof.ads",
                        RB / "proof" / "ring_buffer_client_proof.adb"],
            "sparklib": True,
            "origin": f"examples/ring_buffer scripts/ablate_proof_support.py "
                      f"--only {case}"}


CASES = {
    "ring_no_public_model_bound": _ring("no_public_model_bound"),
    "ring_no_is_empty_post": _ring("no_is_empty_post"),
    "ring_no_is_full_post": _ring("no_is_full_post"),
    "pool_spec_no_count_posts": {
        "results": FP / "obj" / "ablation_spec_no_count_posts" / "gnatprove",
        "sources": [FP / "obj/ablation_src/spec_no_count_posts/fixed_pool.ads",
                    FP / "proof" / "fixed_pool_client_proof.ads",
                    FP / "proof" / "fixed_pool_client_proof.adb"],
        "sparklib": True,
        "origin": "examples/fixed_pool scripts/ablate_proof_support.py "
                  "--only spec_no_count_posts"},
    "pool_false_client_assert": {
        "results": FP / "obj" / "ablation_false_client_assert" / "gnatprove",
        "sources": [FP / "obj/ablation_src/false_client_assert/" / n
                    for n in ("fixed_pool.ads", "fixed_pool_false_client.ads",
                              "fixed_pool_false_client.adb")],
        "sparklib": True,
        "origin": "capture_fixtures.py produce pool_false_client_assert"},
    "conjunct_experiment": {
        "results": EXP / "obj" / "gnatprove",
        "sources": [],   # src/ is the committed experiment itself
        "sparklib": False,
        "origin": "capture_semantic_fixtures.py produce"},
}

GPR = """--  Task 009 semantic snapshot (generated by
--  diagnostics/scripts/capture_semantic_fixtures.py). Source corpus only;
--  never built or proved.
{with_}project Semantic is
   for Source_Dirs use ("src");
   for Object_Dir use "obj";
end Semantic;
"""


def _tokens_checksum(path: Path) -> str | None:
    import libadalang as lal
    unit = lal.AnalysisContext().get_from_file(str(path))
    toks, t = [], unit.first_token
    while t is not None:
        if not t.is_trivia and t.kind != "Termination":
            toks.append(t.text)
        t = t.next
    return gnat_checksum(toks)


def _verified(path: Path, records: dict) -> dict:
    """The D record `path` matches exactly (checksum and timestamp)."""
    ck, ts = _tokens_checksum(path), mtime_stamp(str(path))
    if (ts, ck) not in records.get(path.name, set()):
        raise SystemExit(f"{path}: not the source GNATprove analysed "
                         f"(checksum {ck}, mtime {ts}, .ali: "
                         f"{sorted(records.get(path.name, []))})")
    return {"d_timestamp": ts, "gnat_checksum": ck,
            "sha256": hashlib.sha256(path.read_bytes()).hexdigest()}


def _sanitize_ali(text: str) -> str:
    return "\n".join(l for l in text.splitlines()
                     if l[:2] in ("V ", "U ", "W ", "Z ", "D ")) + "\n"


def collect(name: str, spec: dict) -> None:
    res = spec["results"]
    if not (res / "gnatprove.sarif").is_file():
        raise SystemExit(f"{name}: no result set in {res}")
    records = load_ali_sources(res).records
    dest = OUT / name
    out_res = dest / "results"
    shutil.rmtree(out_res, ignore_errors=True)
    out_res.mkdir(parents=True)
    (out_res / "gnatprove.sarif").write_text(
        cf.sanitize_sarif((res / "gnatprove.sarif").read_text("utf-8")),
        encoding="utf-8")
    for p in sorted(res.glob("*.spark")):
        (out_res / p.name).write_text(cf.sanitize_spark(p.read_text("utf-8")),
                                      encoding="utf-8")
    for p in sorted(res.glob("*.ali")):
        (out_res / p.name).write_text(
            _sanitize_ali(p.read_text("utf-8", errors="replace")),
            encoding="utf-8")
    files = {}
    if spec["sources"]:
        src = dest / "src"
        shutil.rmtree(src, ignore_errors=True)
        src.mkdir(parents=True)
        for s in spec["sources"]:
            meta = _verified(s, records)
            shutil.copy2(s, src / s.name)
            files[f"src/{s.name}"] = meta
        (dest / "semantic.gpr").write_text(GPR.format(
            with_='with "sparklib";\n' if spec["sparklib"] else ""),
            encoding="utf-8")
    else:
        for s in sorted((dest / "src").glob("*.ad[sb]")):
            files[f"src/{s.name}"] = _verified(s, records)
    if name == "conjunct_experiment":
        _experiment_evidence(res, dest)
    snap = {"name": name, "origin": spec["origin"],
            "project": "semantic.gpr" if spec["sources"]
            else "experiment.gpr",
            "needs_sparklib": spec["sparklib"], "sources": files}
    (dest / "snapshot.json").write_text(
        json.dumps(snap, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"collected {name}: {len(files)} verified sources")


EXPERIMENT = {7: "Op: conjunct 1 (Y > 0) unprovable, conjunct 0 holds",
              12: "Op: conjunct 0 (X > 0) unprovable, conjunct 1 holds",
              17: "Op: both conjuncts unprovable",
              22: "Op3: conjunct 1 (Y > 0) unprovable, 0 and 2 hold"}


def _experiment_evidence(res: Path, dest: Path) -> None:
    """Raw .spark evidence the sanitized copy drops: each entry's full key
    set and the per-goal prover results of its check_tree (Why3 goals
    after split_goal_wp_conj; times and step counts removed)."""
    doc = json.loads((res / "client.spark").read_text("utf-8"))
    out = {}
    for e in doc["proof"]:
        if e["rule"] != "VC_PRECONDITION" or e["line"] not in EXPERIMENT:
            continue
        out[str(e["line"])] = {
            "ground_truth": EXPERIMENT[e["line"]],
            "entry_keys": sorted(e),
            "sarif_message": e["message"]["text"],
            "check_tree_goals": [
                {p: v["result"].split("\n")[0]
                 for p, v in sorted(g.get("proof_attempts", {}).items())}
                for g in e.get("check_tree", [])]}
    (dest / "evidence.json").write_text(
        json.dumps(out, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def produce() -> None:
    shutil.rmtree(EXP / "obj", ignore_errors=True)
    cmd = ["alr", "-n", "exec", "--", "gnatprove", "-P",
           str(EXP / "experiment.gpr"), "-j0"]
    print("$", " ".join(cmd), flush=True)
    subprocess.run(cmd, cwd=RB, check=True)


def main() -> int:
    if sys.argv[1:2] == ["produce"]:
        produce()
        return 0
    if sys.argv[1:2] != ["collect"]:
        print(__doc__)
        return 2
    names = sys.argv[2:] or list(CASES)
    for n in names:
        collect(n, CASES[n])
    return 0


if __name__ == "__main__":
    sys.exit(main())
